### ISSUE TITLE
Beth Net Launcher detection not working

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [erri120/GameFinder#10]
In the WJ client at least, the detection of Beth Net is not working.

The log doesn't even mention the launcher.

All tested "known" registry locations had no traces of Morrowind.

**Comment by EzioTheDeadPoet** [comment]
A registry search for `bethnet://` didn't find anything.

**Comment by erri120** [comment]
Try a search for `bethesdanet://uninstall/ `

**Comment by erri120** [comment]
Also make sure to start the game at least once

**Comment by EzioTheDeadPoet** [comment]
Ok it still works. Just unlike Skyrim the game itself needs to start not the launcher. 
So my bad and probably the same reason why it didn't work for that user.
Or rebooting my pc made it register.
