### ISSUE TITLE
Change 'Can't find Manifest Folder / Directory' Errors to warnings

### ISSUE THREAD

**Issue by MichaelPetersen22** [erri120/GameFinder#113]
In Origin Game Finder, Epic Games Finder... Other Games Finders?

Using github actions with wabbajack and it's picking these up as errors and killing the process pre-emptively. Wondering if they could be changed to warnings? Unless there is a specific reason they are exceptions?

**Comment by erri120** [comment]
Handling of library errors is the responsibility of the library consumer.
