### ISSUE TITLE
Add Registry Bounce

### ISSUE THREAD

**Issue by Noggog** [erri120/GameFinder#15]
Just pitching the idea of adding registry support.  Currently mutagen uses GameFinder, but only if it cannot locate an installation in the registry:
https://github.com/Mutagen-Modding/Mutagen/blob/cf708daf0b89c643b94bf08c28e7ab2a719d9451/Mutagen.Bethesda.Core.Windows/Installs/DI/GameLocator.cs#L50

Might be nice to just bubble that up to this lib?  Is there a specific reason registries are not considered?

This would also help with WJ "stock game" installs, which you can see some discussions here:
https://discord.com/channels/759302581448474626/883872997214158909/883872999562960906
https://discord.com/channels/605449136870916175/623261438022254612/883870322581962792

**Comment by erri120** [comment]
What exactly do you mean with
> registry support
Most of the packages already access the registry to find the the Store installation, installed games or both.

**Comment by Noggog** [comment]
Mutagen has code to look at the registry for `SOFTWARE\WOW6432Node\Bethesda Softworks\Skyrim Special Edition`, as a lot of people complained their games weren't being located when just GameFinder was being used by itself.    I was under the impression that GameFinder only returns results from the steam library files, and doesn't look for that registry key ^
