### ISSUE TITLE
Mo2 Ini Sourcing

### ISSUE THREAD

**Issue by Noggog** [erri120/GameFinder#16]
On the topic of #15 where the game might be in atypical locations due to WJ "stock game" installations

If LostDragonist's fix registries Mo2 plugin (https://github.com/LostDragonist/MO2-Plugins) isnt installed, then registry lookups will fail.

Might also be nice to add some logic to sense if the program is being started via mo2, and look to mo2 ini sources for game location?  I'm not too sure the details of what would go into this, but would add another nice layer of robustness

**Comment by erri120** [comment]
Not sure I fully understand the problem but there isn't really a way of detecting whether the application that uses this library was started with MO2 unless you do some process information hacking and figure out what the parent process is or check if the application was started/is located in a sub-directory of an MO2 installation...

The biggest issue is that I want this lib to be universal and not bound to the Bethesda Modding Community. The stock game function of Wabbajack will fuck with anything that tries to locate the game so I would suggest moving this to Wabbajack and if people use this features, they should also use the MO2 registry fix plugin.
