### ISSUE TITLE
Game finder finds no games

### ISSUE THREAD

**Issue by OpenSauce04** [erri120/GameFinder#17]
When trying to grab a list of steam games using the example provided in the readme, it outputs nothing, the collection is blank, and there is no error whatsoever. Why?

**Comment by erri120** [comment]
Can you post your source code?

**Comment by OpenSauce04** [comment]
I don't have what I wrote anymore, as I ended up using a different method, but it was exactly as it is at the top of the readme file
I copy-pasted directly from there

**Comment by erri120** [comment]
The code snippet in the README doesn't provide an `ILogger` to the `SteamHandler`. The code does not throw and instead logs all errors. I suggest looking at the [Example program](https://github.com/erri120/GameFinder/blob/master/GameFinder.Example/Program.cs) which you can also try from the [releases](https://github.com/erri120/GameFinder/releases/download/v1.7.3/GameFinder.Example.zip).
