### ISSUE TITLE
Invalid registry path value for GOG games

### ISSUE THREAD

**Issue by oreze** [erri120/GameFinder#25]
Path to the GOG games registry is invalid (or valid, but not for all cases). In my case GOG games have registry keys under "SOFTWARE\WOW6432Node\GOG.com", not "SOFTWARE\GOG.com" like in the code.

[Link to wrong property](https://github.com/erri120/GameFinder/blob/master/GameFinder.StoreHandlers.GOG/GOGHandler.cs#:~:text=internal%20const%20string%20GOGRegKey%20%3D%20%40%22Software%5CGOG.com%5CGames%22%3B)

![image](https://user-images.githubusercontent.com/22376195/200188961-60752211-41b9-45e3-b4cf-67ff37fa5a89.png)

**Comment by erri120** [comment]
The path `SOFTWARE\GOG.com` is correct. `WOW6432Node` is a result of the difference between 32-bit and 64-bit applications writing to the registry. You can read more [here](https://learn.microsoft.com/en-us/windows/win32/sysinfo/32-bit-and-64-bit-application-data-in-the-registry) and [here](https://learn.microsoft.com/en-us/dotnet/api/microsoft.win32.registryview?view=net-7.0).

The code is actually opening the registry with the 32-bit View:

```csharp
_registry.OpenBaseKey(RegistryHive.LocalMachine, RegistryView.Registry32);
```

Which will expand `SOFTWARE\GOG.com` into `SOFTWARE\WOW6432Node\GOG.com`. You should never explicitly use `WOW6432Node` in a key, but instead use the 32-bit View access.

**Comment by oreze** [comment]
Thanks, I'll keep that in mind.
