### ISSUE TITLE
Publish single file supports?

### ISSUE THREAD

**Issue by wandersonareis** [erri120/GameFinder#46]
C:\Program Files\dotnet\sdk\7.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.CrossTargeting.targets(27,5): erro
r NETSDK1129: não há suporte para o destino 'Publish' sem especificar uma estrutura de destino. O projeto atual se dest
ina a várias estruturas. Você precisa especificar a estrutura do aplicativo publicado.

**Comment by erri120** [comment]
I need more information. What exactly are you trying to do? If you're trying to use dotnet publish and it fails with NETSDK1129, then you might have to specify the target framework.

**Comment by wandersonareis** [comment]
Winforms + blazor with webview2.
With dotnet publish -c release --sc -r win-x64 -p:PublishSingleFile=true --self-contained false

When I am using your nuget or project in zip, my project does not compile using this command.

**Comment by erri120** [comment]
You need to specify the target framework. GameFinder supports net6 and net7. Use -f to specify the framework.

**Comment by wandersonareis** [comment]
Using -f net7, give error about use -windows

**Comment by erri120** [comment]
WinForms is windows only, so you have to use net7-windows which is a subset of net7.

**Comment by wandersonareis** [comment]
worked using your nuget.
I still don't know why it gave an error the other time. I tried using the downloaded project and it didn't work.

So I come to you.
Thanks for your help.
