### ISSUE TITLE
Steam Location Fails if a Universe Missing

### ISSUE THREAD

**Issue by Noggog** [erri120/GameFinder#5]
Synthesis just swapped to using GameFinder as it's backing logic (Mutagen itself swapped a while back, but Synthesis hadn't had a new version that included it until a few days ago).  There have been a few users that have complained that it can't find the Skyrim data folder for them anymore.

I spent some time with Accelerando, who ran GameFinder's demo app, which helped a ton in narrowing down the problem.

Essentially, he had a vestigial steam universe listed
![image](https://user-images.githubusercontent.com/24981326/115471286-9212ee00-a1ec-11eb-844d-1138d7a60301.png)

`C:\Steam` was listed, but apparently didn't actually have ` steamapps` subfolder because they moved all the games to another universe.   This caused a SteamUniverseNotFoundException, to throw.  Skyrim was in the other universes, but those never got around to processing, as the current loop just stops in this situation.

I'd love if the patterns were adjusted so it's not an all or nothing affair?  If 1/3 universes have an issue, I'd love to be able to try to query anyway and cross my fingers that the game I was looking for was in one of the others.

**Comment by erri120** [comment]
Should be resolved with #7
